INSERT INTO especialidades (id_especialidad, especialidad) VALUES ('001', 'PEDIATRIA');
INSERT INTO especialidades (id_especialidad, especialidad) VALUES ('002', 'NUTRICION');
INSERT INTO especialidades (id_especialidad, especialidad) VALUES ('003', 'OFTALMOLOGIA INFANTIL');
INSERT INTO especialidades (id_especialidad, especialidad) VALUES ('005', 'GASTROENTEROLOGIA INFANTIL');
INSERT INTO especialidades (id_especialidad, especialidad) VALUES ('007', 'MEDICINA GENERAL Y FAMILIAR');
INSERT INTO especialidades (id_especialidad, especialidad) VALUES ('008', 'PSICOPEDAGOGIA');
INSERT INTO especialidades (id_especialidad, especialidad) VALUES ('009', 'ODONTOLOGIA INFANTIL');
INSERT INTO especialidades (id_especialidad, especialidad) VALUES ('010', 'APTO ESCOLAR');
INSERT INTO especialidades (id_especialidad, especialidad) VALUES ('011', 'ELECTROCARDIOGRAMA');
INSERT INTO especialidades (id_especialidad, especialidad) VALUES ('012', 'NEUROLOGIA INFANTIL');
INSERT INTO especialidades (id_especialidad, especialidad) VALUES ('013', 'ENDOCRINOLOGIA INFANTIL');
INSERT INTO tipo_turno (id_tipo_turno, tipo_turno) VALUES ('001', 'CONTROL DE ENFERMEDAD');
INSERT INTO tipo_turno (id_tipo_turno, tipo_turno) VALUES ('002', 'CONTROL DE SALUD');
INSERT INTO tipo_turno (id_tipo_turno, tipo_turno) VALUES ('003', 'PRIMERA VEZ');
INSERT INTO tipo_turno (id_tipo_turno, tipo_turno) VALUES ('004', 'SEGUIMIENTO NUTRICION');
INSERT INTO tipo_turno (id_tipo_turno, tipo_turno) VALUES ('005', 'CONSULTA');
INSERT INTO tipo_turno (id_tipo_turno, tipo_turno) VALUES ('006', 'CONSULTA VIRTUAL');
INSERT INTO tipo_turno (id_tipo_turno, tipo_turno) VALUES ('007', 'CONTROL OFTALMOLOGICO');
INSERT INTO tipo_turno (id_tipo_turno, tipo_turno) VALUES ('008', 'RECETAS/ORDENES');
INSERT INTO tipo_turno (id_tipo_turno, tipo_turno) VALUES ('009', 'CONSULTORIO INTEGRAL ADULTXS');
INSERT INTO tipo_turno (id_tipo_turno, tipo_turno) VALUES ('010', 'CONSULTORIO INTEGRAL ADOLESCENTES');
INSERT INTO tipo_turno (id_tipo_turno, tipo_turno) VALUES ('011', 'CONSEJERIA EN SALUD SEXUAL(Y NO) REPRODUCTIVA');
INSERT INTO tipo_turno (id_tipo_turno, tipo_turno) VALUES ('012', 'TELEMEDICINA - CONSULTORIO INTEGRAL ADULTXS / CONSEJERIA EN SALUD SEXUAL(Y NO) REPRODUCTIVA');
INSERT INTO tipo_turno (id_tipo_turno, tipo_turno) VALUES ('013', 'TELEMEDICINA - CONSULTORIO INTEGRAL ADOLESCENTES');
INSERT INTO tipo_turno (id_tipo_turno, tipo_turno) VALUES ('014', 'APTO BUCODENTAL');
INSERT INTO tipo_turno (id_tipo_turno, tipo_turno) VALUES ('015', 'PEDIATRIA y ODONTOLOGIA');
INSERT INTO tipo_turno (id_tipo_turno, tipo_turno) VALUES ('016', 'PEDIATRIA y OFTALMOLOGIA');
INSERT INTO tipo_turno (id_tipo_turno, tipo_turno) VALUES ('017', 'ELECTROCARDIOGRAMA');
INSERT INTO tipo_turno (id_tipo_turno, tipo_turno) VALUES ('018', 'EVALUACION NEUROCOGNITIVA');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('001', '01-01-2022', 'Año Nuevo');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('002', '28-02-2022', 'Carnaval');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('003', '01-03-2022', 'Carnaval');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('004', '24-03-2022', 'Día Nacional de la Memoria por la Verdad y la Justicia');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('005', '02-04-2022', 'Día del Veterano y de los Caídos en la Guerra de Malvinas');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('006', '14-04-2022', 'Jueves Santo');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('007', '15-04-2022', 'Viernes Santo');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('008', '01-05-2022', 'Día del Trabajador');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('009', '18-05-2022', 'Censo nacional 2022');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('010', '25-05-2022', 'Día de la Revolución de Mayo');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('011', '17-06-2022', 'Paso a la Inmortalidad del Gral. Don Martín Miguel de Güemes');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('012', '20-06-2022', 'Paso a la Inmortalidad del Gral. Manuel Belgrano');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('013', '09-07-2022', 'Día de la Independencia');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('014', '15-08-2022', 'Paso a la Inmortalidad del Gral. José de San Martín (17/8)');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('015', '07-10-2022', 'Feriado con fines turísticos');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('016', '10-10-2022', 'Día del Respeto a la Diversidad Cultural (12/10)');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('017', '20-11-2022', 'Día de la Soberanía Nacional');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('018', '21-11-2022', 'Feriado con fines turísticos');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('019', '08-12-2022', 'Inmaculada Concepción de María');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('020', '09-12-2022', 'Feriado con fines turísticos');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('021', '25-12-2022', 'Navidad');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('022', '01-01-2023', 'Año Nuevo');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('023', '20-02-2023', 'Carnaval');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('024', '21-03-2023', 'Carnaval');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('025', '24-03-2023', 'Día Nacional de la Memoria por la Verdad y la Justicia');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('026', '02-04-2023', 'Día del Veterano y de los Caídos en la Guerra de Malvinas');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('027', '06-04-2023', 'Jueves Santo');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('028', '07-04-2023', 'Viernes Santo');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('029', '24-04-2023', 'Día de acción por la tolerancia y el respeto entre los pueblos');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('030', '01-05-2023', 'Día del Trabajador');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('031', '25-05-2023', 'Día de la Revolución de Mayo');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('032', '26-05-2023', 'Feriado con fines turísticos');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('033', '17-06-2023', 'Paso a la Inmortalidad del Gral. Don Martín Miguel de Güemes');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('034', '19-06-2023', 'Feriado con fines turísticos');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('035', '20-06-2023', 'Paso a la Inmortalidad del Gral. Manuel Belgrano');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('036', '09-07-2023', 'Día de la Independencia');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('037', '21-08-2023', 'Paso a la Inmortalidad del Gral. José de San Martín (17/8)');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('038', '13-10-2023', 'Feriado con fines turísticos');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('039', '16-10-2023', 'Día del Respeto a la Diversidad Cultural (12/10)');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('040', '20-11-2023', 'Día de la Soberanía Nacional');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('041', '08-12-2023', 'Inmaculada Concepción de María');
INSERT INTO feriados (id_feriado, fecha, detalle) VALUES ('042', '25-12-2023', 'Navidad');